services:
  phoenix:
    build: .
    command: sh -c "mix deps.get && mix ecto.setup && mix phx.server"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      MIX_ENV: dev
      DATABASE_URL: ecto://postgres:postgres@db/postgres
    depends_on:
      - db
  
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
